### PR TITLE
Support a MCP23017 backend

### PR DESCRIPTION
**Pull request by rm-hull**
Hi, I made a few changes to your HD44780 python library:
- Changed tabs into spaces (see here for why: http://www.python.org/dev/peps/pep-0008/#tabs-or-spaces)
- Cleaned up some old directories
- Removed old references to HD47780 - it is known as a HD44780
- Added a new backend: the MCP23017 16-bit I/O buffer
- _examples/interaction.py_ modifed to use the MCP23017 backend
- Bumped version to 1.1.3

Great work, BTW

Regards
Richard

### CODE REVIEW

**Comment by CatoLynx** [comment]
Thanks for your efforts, but I refuse to accept this pull request unless you change the spaces back into tabs. I will never use spaces, I'll stick to tabs.

**Comment by CatoLynx** [comment]
Also, this project is deprecated. Please make your changes to my new pyLCD repository.

**Comment by rm-hull** [comment]
No problem - I'll re-apply the backend to the new project (with tabs)

**Comment by CatoLynx** [comment]
Thank you very much!

**Pull request closed without merging**
